### PR TITLE
Fix pull request commit SHA reference

### LINKED ISSUE #1: Deployment working but not showing up in pull requests
Hey @eliperelman, just wondering if there is any extra setup needed. I've gone through the steps stated in an example repo so I can understand everything. Travis builds my assets and tests and goes through now-travis and when checking my now.sh account I see the new instance but it's not showing on the PR.

Just to add I am not limited by the amount of instances. Any insight into what I might need to change?

### PR DESCRIPTION
**Pull request by kentcdodds**
Closes #1

### CODE REVIEW

**Comment by kentcdodds** [comment]
[Here's an example](https://github.com/kentcdodds/glamorous-website/pull/34) of a working pull request with these changes ([build](https://travis-ci.org/kentcdodds/glamorous-website/builds/238339108)).

**Review by eliperelman — APPROVED** [review]
This look great, thank you very much!

**Comment by eliperelman** [comment]
Published to npm at v1.0.1.

**Comment by kentcdodds** [comment]
Sweet! Thanks!

**Pull request merged**
